services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: weeklyscore
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: myuser@example.com
      PGADMIN_DEFAULT_PASSWORD: mypass
    ports:
      - 5050:80

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redisinsight:
    image: "redis/redisinsight:latest"
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/db

volumes:
  redisinsight-data:

networks:
  default:
    name: local-pg-network
    driver: bridge
